services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  php:
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      APP_SECRET: "${APP_SECRET}"
    volumes:
      - .:/var/www/html
      - cache_data:/var/www/html/var/cache
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - symfony

volumes:
  db_data:
  cache_data:

networks:
  symfony:
